//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace MegaStar.Data.Library.Entities
{
    public partial class MegaStarzEntities : ObjectContext
    {
        public const string ConnectionString = "name=MegaStarzEntities";
        public const string ContainerName = "MegaStarzEntities";
    
        #region Constructors
    
        public MegaStarzEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MegaStarzEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public MegaStarzEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Star> Stars
        {
            get { return _stars  ?? (_stars = CreateObjectSet<Star>("Stars")); }
        }
        private ObjectSet<Star> _stars;
    
        public ObjectSet<Song> Songs
        {
            get { return _songs  ?? (_songs = CreateObjectSet<Song>("Songs")); }
        }
        private ObjectSet<Song> _songs;
    
        public ObjectSet<Artist> Artists
        {
            get { return _artists  ?? (_artists = CreateObjectSet<Artist>("Artists")); }
        }
        private ObjectSet<Artist> _artists;
    
        public ObjectSet<SongStarLink> SongStarLinks
        {
            get { return _songStarLinks  ?? (_songStarLinks = CreateObjectSet<SongStarLink>("SongStarLinks")); }
        }
        private ObjectSet<SongStarLink> _songStarLinks;

        #endregion
    }
}
