//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MegaStar.Data.Library.Entities
{
    public partial class SongStarLink
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual System.DateTime InsertDate
        {
            get;
            protected set;
        }
    
        public virtual int StarId
        {
            get { return _starId; }
            protected set
            {
                if (_starId != value)
                {
                    if (Star != null && Star.Id != value)
                    {
                        Star = null;
                    }
                    _starId = value;
                }
            }
        }
        private int _starId;
    
        public virtual int SongId
        {
            get { return _songId; }
            protected set
            {
                if (_songId != value)
                {
                    if (Song != null && Song.Id != value)
                    {
                        Song = null;
                    }
                    _songId = value;
                }
            }
        }
        private int _songId;
    
        public virtual string FileGuid
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Star Star
        {
            get { return _star; }
            set
            {
                if (!ReferenceEquals(_star, value))
                {
                    var previousValue = _star;
                    _star = value;
                    FixupStar(previousValue);
                }
            }
        }
        private Star _star;
    
        public virtual Song Song
        {
            get { return _song; }
            set
            {
                if (!ReferenceEquals(_song, value))
                {
                    var previousValue = _song;
                    _song = value;
                    FixupSong(previousValue);
                }
            }
        }
        private Song _song;

        #endregion
        #region Association Fixup
    
        private void FixupStar(Star previousValue)
        {
            if (previousValue != null && previousValue.SongStarLinks.Contains(this))
            {
                previousValue.SongStarLinks.Remove(this);
            }
    
            if (Star != null)
            {
                if (!Star.SongStarLinks.Contains(this))
                {
                    Star.SongStarLinks.Add(this);
                }
                if (StarId != Star.Id)
                {
                    StarId = Star.Id;
                }
            }
        }
    
        private void FixupSong(Song previousValue)
        {
            if (previousValue != null && previousValue.SongStarLinks.Contains(this))
            {
                previousValue.SongStarLinks.Remove(this);
            }
    
            if (Song != null)
            {
                if (!Song.SongStarLinks.Contains(this))
                {
                    Song.SongStarLinks.Add(this);
                }
                if (SongId != Song.Id)
                {
                    SongId = Song.Id;
                }
            }
        }

        #endregion
    }
}
