//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MegaStar.Data.Library.Entities
{
    public partial class Star
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            protected set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual System.DateTime InsertDate
        {
            get;
            protected set;
        }
    
        public virtual System.DateTime UpdateDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<SongStarLink> SongStarLinks
        {
            get
            {
                if (_songStarLinks == null)
                {
                    var newCollection = new FixupCollection<SongStarLink>();
                    newCollection.CollectionChanged += FixupSongStarLinks;
                    _songStarLinks = newCollection;
                }
                return _songStarLinks;
            }
            set
            {
                if (!ReferenceEquals(_songStarLinks, value))
                {
                    var previousValue = _songStarLinks as FixupCollection<SongStarLink>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupSongStarLinks;
                    }
                    _songStarLinks = value;
                    var newValue = value as FixupCollection<SongStarLink>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupSongStarLinks;
                    }
                }
            }
        }
        private ICollection<SongStarLink> _songStarLinks;

        #endregion
        #region Association Fixup
    
        private void FixupSongStarLinks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (SongStarLink item in e.NewItems)
                {
                    item.Star = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SongStarLink item in e.OldItems)
                {
                    if (ReferenceEquals(item.Star, this))
                    {
                        item.Star = null;
                    }
                }
            }
        }

        #endregion
    }
}
